server:
  port: 9090

  servlet:
    context-path: /api/pci


spring:
  application:
    name: pci-vault

  profiles:
    active: bill
    default: bill


  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    database: MYSQL
    hibernate:
      ddl-auto: update


security:
  iv: "22d2b48279af3df6"
  key: "61f22f21-1fdc-45f1-acee-2a8a2bfc"


