spring:
  application:
    name: pci-vault

  profiles:
    active: bill


  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    database: MYSQL
    hibernate:
      ddl-auto: update
